/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9cfc184bb7dcad5ac3a76a6da3036312)
interface __BaseEnv_Env {
	DOCUMENTS: KVNamespace;
	VAULTGRAM_DB: D1Database;
	DELETE_QUEUE: Queue;
	MAX_FILE_BYTES: "20000000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAX_FILE_BYTES">> {}
}
