PRAGMA foreign_keys = ON;
CREATE TABLE workspaces (id TEXT PRIMARY KEY, name TEXT NOT NULL DEFAULT 'Workspace', owner_user_id TEXT UNIQUE, bootstrap_closed INTEGER NOT NULL DEFAULT 0 CHECK(bootstrap_closed IN (0,1)), created_at INTEGER NOT NULL);
CREATE TABLE users (id TEXT PRIMARY KEY, telegram_id TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('OWNER','MEMBER')), disabled INTEGER NOT NULL DEFAULT 0 CHECK(disabled IN (0,1)), removed INTEGER NOT NULL DEFAULT 0 CHECK(removed IN (0,1)), locale TEXT CHECK(locale IN ('en','fa')), pin_salt TEXT, pin_hash TEXT, pin_failures INTEGER NOT NULL DEFAULT 0, pin_locked_until INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE UNIQUE INDEX users_single_owner_idx ON users(role) WHERE role='OWNER';
CREATE TABLE vaults (id TEXT PRIMARY KEY, name TEXT NOT NULL, requires_pin INTEGER NOT NULL DEFAULT 0 CHECK(requires_pin IN (0,1)), archived_at INTEGER, created_at INTEGER NOT NULL);
CREATE INDEX vaults_archived_name_idx ON vaults(archived_at,name);
CREATE TABLE categories (id TEXT PRIMARY KEY, vault_id TEXT NOT NULL REFERENCES vaults(id), name TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE INDEX categories_vault_idx ON categories(vault_id,sort_order);
CREATE TABLE documents (id TEXT PRIMARY KEY, vault_id TEXT NOT NULL REFERENCES vaults(id), category_id TEXT NOT NULL REFERENCES categories(id), title TEXT NOT NULL, original_filename TEXT NOT NULL, mime_type TEXT NOT NULL, size_bytes INTEGER NOT NULL CHECK(size_bytes >= 0), drive_item_id TEXT NOT NULL, drive_etag TEXT, storage_name TEXT NOT NULL, telegram_file_id TEXT, telegram_unique_id TEXT, status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','ARCHIVED','MISSING','DELETING')), created_by TEXT NOT NULL REFERENCES users(id), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, last_checked_at INTEGER NOT NULL DEFAULT 0);
CREATE INDEX documents_category_idx ON documents(category_id,status,created_at);
CREATE UNIQUE INDEX documents_drive_item_idx ON documents(drive_item_id);
CREATE INDEX documents_reconcile_idx ON documents(status,last_checked_at);
CREATE TABLE vault_permissions (user_id TEXT NOT NULL REFERENCES users(id), vault_id TEXT NOT NULL REFERENCES vaults(id), level TEXT NOT NULL CHECK(level IN ('VIEW','EDIT','MANAGE')), PRIMARY KEY(user_id,vault_id));
CREATE INDEX permissions_vault_idx ON vault_permissions(vault_id);
CREATE TABLE invites (id TEXT PRIMARY KEY, token_hash TEXT NOT NULL UNIQUE, expires_at INTEGER NOT NULL, used_at INTEGER, used_by TEXT, revoked_at INTEGER, created_by TEXT NOT NULL REFERENCES users(id), created_at INTEGER NOT NULL);
CREATE TABLE invite_permissions (invite_id TEXT NOT NULL REFERENCES invites(id), vault_id TEXT NOT NULL REFERENCES vaults(id), level TEXT NOT NULL CHECK(level IN ('VIEW','EDIT','MANAGE')), PRIMARY KEY(invite_id,vault_id));
CREATE TABLE oauth_connections (id INTEGER PRIMARY KEY CHECK(id=1), access_cipher TEXT NOT NULL, refresh_cipher TEXT NOT NULL, expires_at INTEGER NOT NULL, version INTEGER NOT NULL DEFAULT 1, connected_at INTEGER NOT NULL);
CREATE TABLE oauth_states (state_hash TEXT PRIMARY KEY, expires_at INTEGER NOT NULL, used_at INTEGER, user_id TEXT NOT NULL REFERENCES users(id));
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE user_sessions (user_id TEXT PRIMARY KEY REFERENCES users(id), state TEXT, payload TEXT, expires_at INTEGER NOT NULL DEFAULT 0, pin_unlocked_until INTEGER NOT NULL DEFAULT 0, menu_message_id INTEGER);
CREATE TABLE pending_actions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), kind TEXT NOT NULL, payload TEXT NOT NULL, expires_at INTEGER NOT NULL, consumed_at INTEGER);
CREATE INDEX pending_actions_user_idx ON pending_actions(user_id,expires_at);
CREATE TABLE audit_logs (id TEXT PRIMARY KEY, actor_user_id TEXT, event TEXT NOT NULL, target_id TEXT, context TEXT, created_at INTEGER NOT NULL);
CREATE INDEX audit_recent_idx ON audit_logs(created_at DESC);
CREATE TABLE processed_telegram_updates (update_id INTEGER PRIMARY KEY, created_at INTEGER NOT NULL);
CREATE TABLE cleanup_jobs (id TEXT PRIMARY KEY, drive_item_id TEXT NOT NULL, reason TEXT NOT NULL, created_at INTEGER NOT NULL, completed_at INTEGER);
CREATE INDEX cleanup_pending_idx ON cleanup_jobs(completed_at,created_at);
CREATE TABLE upload_receipts (chat_id TEXT NOT NULL, message_id INTEGER NOT NULL, document_id TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY(chat_id,message_id));
INSERT INTO workspaces(id,name,bootstrap_closed,created_at) VALUES('default','Workspace',0,unixepoch());
INSERT INTO settings(key,value) VALUES ('default_locale','en'),('delete_after_seconds','120'),('delete_incoming','true'),('protect_content','true'),('pin_policy','OFF'),('invite_expiry_hours','48'),('pin_session_seconds','600');
